branches: master

addons:
  homebrew:
    packages: python

install: pip3 install tox
script: tox

deploy:
  provider: pypi
  distributions: bdist_wheel
  user: __token__
  password:
    secure: PblLxa3R4N+I0MOoMbyDCoc7OQi6MP8nw1Auw/LYSgq59j1azQQu2AwRgjyWTvViyrOalsw2/Gopt/GgLMW8bFxPTDU9ZUc0WxXF3vm3p5C6oquAU3TpGQyRH1ylnTxTEs0U7bzS7AT5k0r7SUn965tWO6Ju7J6gxfVuDmYOCzZpYQtrIOKSi4MQVAWyjoU2vGVKZypmXdhYqAUATlhE7pjkOzAbVeOjRCf4rFX0BLlFYvOvNoair1zgc2gPMrv6rZ7aQmdjkS9LxIM2614ORfPc7pPZuAUFlNuXn22pmx7Kkn/d73AmONDtXmKcc6vq5+0awR5BmCb3a7dtU4c0JTRfr9VEYBHHP9koF1NsooACVCKaqpfg6wvrrp4uK8nLiGFOaN8kxDfqrdL2lEzJiEoff2rV7e0RmRXLqXY5vQL2XqFd5r+cd2pR7SKfSToXm0kAjSaxe+/WdKPEewuhX1vCYqZJX3HBatYJNRjc8bLcpB7Mk/pYalbREOHry+umoU+iB+Fhg7QC+Mtmohcqzsmch5sBH2sYj9M5Hwh1bauf+eQbBphtrZoL0CitAVSCpPk9iXkiJ4PaP5bCWW8USZxG48JhlXby4WHbDnQE+GPgqZRpp6MNTJugzZ32SOmCXp0bLnHmbs8pKigm18JOeqeOlN0vJVPu1w3/FkDwJw8=
  on:
    tags: true
    repo: joelfrederico/bprof

os: osx

osx_image:
  - xcode11.2
  - xcode10.1
  - xcode9.2
  - xcode8
  - xcode6.4

jobs:
  include:
    - deploy:
        distributions: sdist
