language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: joelfrederico
  password:
    secure: tXHucvakB0wsuphPXj9pTahIkRIePya9Z7dxrdrCg6yi0OjTA4bOTFp0kPEcRpPo972+xznGN7NNokWaij/TLpH0dROxNYQ3huUjpxnIniTfvWoelRFq2L9N0SAXBjd0qyDnKHtkVMMBgAXFi1YgYRioV25EFV9JBInMzJPI1s6CKWA3MWhh8HC410GuPguuLaVGKdWwso+IX+IRI0EO4heDhNGcf4tDzaqnszjLoMYGNnxYoJcxS2xiY679Z9AWFowz4+ZPDsizViAt/xnAO2TvK8PQbQhT+O9rvm3GEMiwFlLEEuDd/b6+B+xYZ51JQRO6P9QgpiZbMhR/Yl22AhnMLIO6Fob7KifuvyfSSe6czdsowuWCAtt3xYsNMiH36YVdX8Dw0UOARQ6oeq7S07uSko8nW9DYzUGuq5qj2eDjle7b3wAer91gqEK4JZTf15ramff6m/PE6uveBpF+/Pi4sZ23Zofz+OtEfNpd+7w4U8a3STVKataiwmY34WL4vX3Zx+J3WSl2ZqbgZ44gwFhaMuO2XvCuA98/ohoyh/cv4HZhwgjRzV4kzjOvSA/HVmcKFbxAYrZVf9Rw5fxy6yCdlIDSlmbQb3J770/zWrn7ZlPpKw2rCJsk34/d4UtyGNvCpksebpXX/SBpwX/h+IbwnMPDKQGR18szgXWO2BM=
  on:
    tags: true
    repo: joelfrederico/bprof
    python: 3.7
