language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist
  user: joelfrederico
  password:
    secure: k6lyPVJq0t2T5EccY5nLgmwA+TMiXzfGtZdx9YNjHWEib8buytgI9D2Qd8BDC1S8bYMw8K3MmuTBChfk55VkBNGJXAqIr8K+g6GKmot5BjDJbVmfhiBVL03RW50F4eXAbAQCzcEyIGW0KW5BEyTv3ku3pJxSn3qMzKsXblsYdgvTulLA2fwL8t1Kb+LXBR/v93bvyiUPbK2cemTFKcjskS3Tzlbw89vW0FqaLYPuOmYqpbnpQYe45rU0dZSyPIuQjZeDOOV3ptqDs4nq1uiow3FTVyFTv2eX+eKjE47uaQfCYyvlpCN/1gDUbJ7XO9LC91vxj0+qMjrRclfjcnWSjWws2+RsJkn7hoo1WiVopkwVBsfL8OuZB9donQXHzA9p1vshKkJ2iIfyiueqZxdPcWQCtusPulS2YuYVpq6jH5WDWEDsVhvnF1dB8DL8OjGOkp3wjVIDg5hexdYcq+R6CyQdKt/5a8F9FFEEOjFpMo9vdjKhwC8zF6FR8jRKaax4sT+CFdUs7+2LKJkpDIhLRc6ZBzOuzW9+IzLZFSNBoXqsH8UKo4+UyZhXtFAj8xioh7tygEegif4I9t8u0U2TZos2NNx+PeKbsnoQnQyiirOWeEBg/i9qY9eEcp2j69lfGqehojtiCKI42bQkowG91pCUu7PqBorbsrWtGOdH0l0=
  on:
    tags: true
    repo: joelfrederico/bprof
    python: 3.7
